### ISSUE TITLE
Error when enabling httpResponseHeaders

### ISSUE THREAD

**Issue by Gallaecio** [scrapy-plugins/scrapy-zyte-api#21] opened 2022-05-25 09:01 UTC
I believe this is a known issue already, but I don’t see it in the tracker.

```python
from scrapy import Request, Spider


class ToScrapeSpider(Spider):
    name = 'toscrape_com'

    custom_settings = {
        'DOWNLOAD_HANDLERS': {
            'http': 'scrapy_zyte_api.handler.ScrapyZyteAPIDownloadHandler',
            'https': 'scrapy_zyte_api.handler.ScrapyZyteAPIDownloadHandler',
        },
        'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor',
    }

    def start_requests(self):
        yield Request(
            'https://toscrape.com',
            meta={
                'zyte_api': {
                    'httpResponseBody': True,
                    'httpResponseHeaders': True,
                },
            },
        )

    def parse(self, response):
        respone.text
```

causes

```
2022-05-25 11:00:15 [scrapy.core.scraper] ERROR: Error downloading <GET https://toscrape.com>
Traceback (most recent call last):
  File "/home/adrian/.local/share/venv/docs.zyte.com/lib/python3.10/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
StopIteration: <200 https://toscrape.com/>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adrian/.local/share/venv/docs.zyte.com/lib/python3.10/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/home/adrian/.local/share/venv/docs.zyte.com/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 60, in process_response
    response = yield deferred_from_coro(method(request=request, response=response, spider=spider))
  File "/home/adrian/.local/share/venv/docs.zyte.com/lib/python3.10/site-packages/scrapy/downloadermiddlewares/httpcompression.py", line 62, in process_response
    decoded_body = self._decode(response.body, encoding.lower())
  File "/home/adrian/.local/share/venv/docs.zyte.com/lib/python3.10/site-packages/scrapy/downloadermiddlewares/httpcompression.py", line 82, in _decode
    body = gunzip(body)
  File "/home/adrian/.local/share/venv/docs.zyte.com/lib/python3.10/site-packages/scrapy/utils/gz.py", line 27, in gunzip
    chunk = f.read1(8196)
  File "/usr/lib/python3.10/gzip.py", line 314, in read1
    return self._buffer.read1(size)
  File "/usr/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.10/gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.10/gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'<!')
```

**Comment by kmike** [comment] 2022-05-25 11:18
I think that's a duplicate of https://github.com/scrapy-plugins/scrapy-zyte-api/issues/11. We probably shouldn't have closed GH-11, as the fix is not in the master branch,

**Closed by kmike** 2022-05-25 11:18 UTC
Labels: bug
